### ISSUE TITLE
how to find the real world location from pixel coordinates

### ISSUE THREAD

**Issue by NandiniCS** [ManishSahu53/read_thermal_temperature#2]
After getting the temperature values of each pixel coordinates,how to find real world location of each pixel using each pixel coordinates?

**Comment by ManishSahu53** [comment]
@NandiniCS ,
If you want to get approx coordinate, then simply use image coordinates (lat, long, elevation). 
If you want to get exact coordinate, then you have perform sfm( Structure from motion) and backproject pixel coordinates to world coordinates

**Comment by NandiniCS** [comment]
Thank you for your reply.
